name: Builds
on:
  push:
  pull_request:

env:
  # From https://learn.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-icon-step-3-install-wdk
  WDK_INSTALLER_URL: "https://go.microsoft.com/fwlink/?linkid=2307500"

jobs:
  test-msvc-wine-linux:
    # Using a pinned version of Ubuntu here; this determines the version of
    # Wine that gets installed - the version of wine-mono that is installed
    # below depends on the host version of Wine.
    runs-on: ubuntu-24.04
    steps:
      - name: Install prerequisites
        run: |
          sudo dpkg --add-architecture i386 && sudo apt-get update
          sudo apt-get update && sudo apt-get install wine64 wine32 python3 msitools ca-certificates cmake ninja-build winbind meson
          WINE=$(command -v wine64 || command -v wine || false)
          $WINE wineboot
          # Check https://gitlab.winehq.org/wine/wine/-/wikis/Wine-Mono#versions before updating the WINE package!
          curl -s -L -O https://github.com/madewokherd/wine-mono/releases/download/wine-mono-8.1.0/wine-mono-8.1.0-x86.msi
          $WINE msiexec /i wine-mono-8.1.0-x86.msi
      - uses: actions/checkout@v4
      - name: Download MSVC
        run: |
          WDK_INSTALLERS=$(./wdk-download.sh --cache /var/tmp/msvc-wine "$WDK_INSTALLER_URL")
          echo Downloaded WDK installers to $WDK_INSTALLERS
          ./vsdownload.py --accept-license --dest $(pwd)/msvc --cache /var/tmp/msvc-wine --with-wdk-installers "$WDK_INSTALLERS"
          ./install.sh $(pwd)/msvc
      - name: Test using the installed tools
        run: |
          HAVE_WDK=1 test/test.sh $(pwd)/msvc
      # Intentionally not storing any artifacts with the downloaded tools;
      # the installed files aren't redistributable!
